replicaCount: 1
image:
  repository: pashok2398/paveld-rads
  tag: 1.0.3
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8080
ingress:
  enabled: true
  className: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
  hosts:
    - host: paveld-rads.druyan.net
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: paveld-rads-tls
      hosts:
        - paveld-rads.druyan.net
resources: {}
