apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-nodejs
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/pashok2398/paveld-rads-gitops
    targetRevision: HEAD
    path: sample-nodejs
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
